apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: prod

resources:
- ingress.yaml

configMapGenerator:
  - name: config
    behavior: merge
    files:
      - config/config.json