apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: base

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: config
    files:
      - config/default.json