image: docker:19.03.1
services:
  - docker:dind

stages:
  - build
  - deploy
  
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

deploy_dev_manual:
  stage: deploy
  image: bitnami/kubectl:1.14.3
  script:
    - kubectl apply -n base-dev --kubeconfig $KUBECONFIG_DEV -f k8s/
  when:
    manual

deploy_dev_kustomize:
  stage: deploy
  image: bitnami/kubectl:1.14.3
  script:
    - kubectl apply --kubeconfig $KUBECONFIG_DEV -k kustomize/overlays/dev/
  when:
    manual

deploy_prod_kustomize:
  stage: deploy
  image: bitnami/kubectl:1.14.3
  script:
    - kubectl apply --kubeconfig $KUBECONFIG_PROD -k kustomize/overlays/prod/
  when:
    manual