apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gitlab.pyaillet.tech:5050/nc-kubernetes/base
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    path: ./kustomize/overlays/local
