apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-owner
rules:
- apiGroups: ["*"]
  resources: ["pods", "pods/log", "deployments", "replicasets", "ingresses", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]